api_platform:
  mapping:
    paths:
      - '%kernel.project_dir%/src/Entity'
      - '%kernel.project_dir%/src/ApiPlatform/Entity'
  patch_formats:
    json: [ 'application/merge-patch+json' ]
  swagger:
    versions: [ 3 ]
  defaults:
    item_operations: [ 'get' ]
    collection_operations: [ 'get' ]
    cache_headers:
      max_age: 3600
    pagination_client_items_per_page: true
    pagination_maximum_items_per_page: 100
